<?php
 include "conexion.php";
 include "claseUsuario.php";
 include "claseUsuarioDAO.php";
 include "claseTipoUsuario.php";
 include "Mascota.php";
 include "MascotaDAO.php";
 include "TipoMascotaDAO.php";
 include "TipoMascota.php";
 include "Cita.php";
 include "CitaDAO.php";
 include "DoctorDAO.php";
 include "Doctor.php";
 include "TipoCitaDAO.php";
 include "TipoCita.php";
 $nombre=$_POST['NombreU'];
 $uDAO=new UsuarioDAO($conn);
 $u=$uDAO->buscaUsuario($nombre);
  $nombreM=$_POST['NombreM']; 
  $tipoM=$_POST['tipoma'];
  $tDAO= new TipoMascotaDAO($conn);
  $tip=$tDAO->buscaTipoMascota($tipoM); 
  $m=new Mascota(1,$nombreM,$tip);
  $mDAO=new MascotaDAO($conn);
  $mDAO->insertaMascota($m);
  $idMas=$mDAO->buscaIdMascota($nombreM);
  $m->setIdMascota($idMas);
  $tipoCi=new TipoCitaDAO($conn);
  $tipoci=$_POST['tipoci'];
  $tipoCita=$tipoCi->buscaTipoCita($tipoci);
  $docDao=new DoctorDAO($conn);
  $doc=$_POST['doc'];
  $doc1=$docDao->buscaDoctor($doc);
  $date = Date('Y-m-d');
  $fecha=$_POST['fecha'];
  //echo $doc1->toString();
  $cita= new Cita(1,$fecha,$date,$tipoCita,$doc1,$m,$u);
  //echo $cita->toString();
  $citaDa=new CitaDAO($conn);
  $citaDa->insertaCita($cita);
?>